[package]
name = "circom-2-arithc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="circom"
path="./src/main.rs"

[dependencies]

serde_json = "1.0"

serde = { workspace = true, optional = true, features = ["derive"] }
serde_arrays = { workspace = true, optional = true }

# dsl
circom-circom =  { git = "https://github.com/iden3/circom", package = "circom"}
circom-compiler =  { git = "https://github.com/iden3/circom", package = "compiler"}
circom-type_analysis =  { git = "https://github.com/iden3/circom", package = "type_analysis"}
circom-circom_algebra =  { git = "https://github.com/iden3/circom", package = "circom_algebra"}
circom-constraint_list =  { git = "https://github.com/iden3/circom", package = "constraint_list"}
circom-program_structure =  { git = "https://github.com/iden3/circom", package = "program_structure"}
circom-constraint_generation =  { git = "https://github.com/iden3/circom", package = "constraint_generation"}
circom-constraint_writers =  { git = "https://github.com/iden3/circom", package = "constraint_writers"}
circom-constant_tracking =  { git = "https://github.com/iden3/circom", package = "constant_tracking"}
circom-code_producers =  { git = "https://github.com/iden3/circom", package = "code_producers"}
circom-dag =  { git = "https://github.com/iden3/circom", package = "dag"}
circom-parser =  { git = "https://github.com/iden3/circom", package = "parser"}
